/* tslint:disable */
/* eslint-disable */
/**
 * Beneficiaires
 * Exemple d\'API REST implémentée par le use-case [uc-ctrl-rest-openapi](http://gitlab.com/stump/kits-java/developpement/usecases-web/uc-ctrl-rest-openapi) du starter-kit STUMP Service.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: ddst-back-per.cnam@assurance-maladie.fr
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

